//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Crud_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails
    {
        public string empid { get; set; }
        public string Name { get; set; }
        public string Addr { get; set; }
        public string Phno { get; set; }
        public Nullable<int> Sal { get; set; }
        public string City { get; set; }
        public string Gen { get; set; }
        public string Dep { get; set; }
        public string Cmp { get; set; }
    }
}
