//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Crud_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string Mailid { get; set; }
        public string Pwd { get; set; }
        public string Name { get; set; }
        public string Adr { get; set; }
        public string Phno { get; set; }
        public string Pin { get; set; }
        public string City { get; set; }
        public string Gen { get; set; }
        public string Upic { get; set; }
    }
}
