//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Crud_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCountry
    {
        public TblCountry()
        {
            this.Tblstate = new HashSet<Tblstate>();
        }
    
        public int Cid { get; set; }
        public string Cname { get; set; }
    
        public virtual ICollection<Tblstate> Tblstate { get; set; }
    }
}
